version: 2.1

jobs:
  check-links:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Lychee
          command: |
            curl -L https://github.com/lycheeverse/lychee/releases/download/v0.14.3/lychee-v0.14.3-x86_64-unknown-linux-gnu.tar.gz > lychee.tar.gz
            tar xzf lychee.tar.gz
            sudo mv ./lychee /usr/local/bin/
      - run:
          name: Run Lychee
          command: |
            lychee --config lychee.toml --quiet ./pages
            if [ $? -ne 0 ]; then
              echo "Lychee found broken links"
              exit 1
            fi

workflows:
  version: 2
  check-links:
    jobs:
      - check-links